In [3]:
import sys
import platform
import jupyter_core

print("Python version:", sys.version)
print("Python executable:", sys.executable)
print("Platform:", platform.platform())
print("Jupyter core version:", jupyter_core.__version__)

# Check if basic Python operations work
try:
    x = 1 + 1
    print("Basic math works:", x)
    
    # Test imports
    import os
    import numpy as np
    print("NumPy version:", np.__version__)
    
    print("Python appears to be working correctly!")
    
except Exception as e:
    print("Error encountered:", str(e))
    print("Error type:", type(e).__name__)

Python version: 3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]
Python executable: C:\ProgramData\anaconda3\python.exe
Platform: Windows-11-10.0.26200-SP0
Jupyter core version: 5.8.1
Basic math works: 2
NumPy version: 2.3.5
Python appears to be working correctly!

In [6]:
import numpy as np
arr=np.array([1.1,2.3,3.4])
print(arr.dtype)
arr_int=arr.astype(np.int32)
print(arr_int)
print(arr_int.dtype)

float64
[1 2 3]
int32

In [10]:
import numpy as np
arr=np.array([100000,30000,50000])
print(arr.dtype)
arr_intsm=arr.astype(np.int32)
print(arr_intsm)
print(arr_intsm.dtype)

int64
[100000  30000  50000]
int32

In [2]:
import pandas as pd
df=pd.read_csv("data.csv")
print(df)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [3]:
pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\programdata\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\programdata\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd
# creating the DataFrame
marks_data = pd.DataFrame({
    'ID': {0: 23, 1: 43, 2: 12,
           3: 13, 4: 67, 5: 89,
           6: 90, 7: 56, 8: 34},

    'Name': {0: 'Ram', 1: 'Deep',
             2: 'Yash', 3: 'Aman',
             4: 'Arjun', 5: 'Aditya',
             6: 'Divya', 7: 'Chelsea',
             8: 'Akash'},

    'Marks': {0: 89, 1: 97, 2: 45, 3: 78,
              4: 56, 5: 76, 6: 100, 7: 87,
              8: 81},

    'Grade': {0: 'B', 1: 'A', 2: 'F', 3: 'C',
              4: 'E', 5: 'C', 6: 'A', 7: 'B',
              8: 'B'}
})

# determining the name of the file
file_name = 'MarksData.xlsx'

# saving the excel
marks_data.to_excel(file_name)
print('DataFrame is written to Excel File successfully.')

df = pd.read_excel("MarksData.xlsx")

print(df)

DataFrame is written to Excel File successfully.
   Unnamed: 0  ID     Name  Marks Grade
0           0  23      Ram     89     B
1           1  43     Deep     97     A
2           2  12     Yash     45     F
3           3  13     Aman     78     C
4           4  67    Arjun     56     E
5           5  89   Aditya     76     C
6           6  90    Divya    100     A
7           7  56  Chelsea     87     B
8           8  34    Akash     81     B

In [7]:
import pandas as pd
s=pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [10]:
import pandas as pd  # Import pandas library first

s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])  # Fixed: added missing ']' and corrected index parameter syntax
print(s)

a    10
b    20
c    30
dtype: int64

In [14]:
import pandas as pd
data={
    'name':['alice','mumbai','charles'],
    'age' :[25,30,35],
    'city':['jaipur','banglore','chennai']
}
df=pd.DataFrame(data)
print(df)

      name  age      city
0    alice   25    jaipur
1   mumbai   30  banglore
2  charles   35   chennai

In [15]:
print(df.index)

RangeIndex(start=0, stop=3, step=1)

In [18]:
print(df.columns)

Index(['name', 'age', 'city'], dtype='object')

In [19]:
df.index=["a","b","c"]
print(df)

      name  age      city
a    alice   25    jaipur
b   mumbai   30  banglore
c  charles   35   chennai

In [22]:
df.columns=['Name','Age','City']
print(df)

      Name  Age      City
a    alice   25    jaipur
b   mumbai   30  banglore
c  charles   35   chennai

In [25]:
import numpy as np
import pandas as pd
arr=np.array([[1,2],[3,4]])
df=pd.DataFrame(arr,columns=['A','B'])
print(df)

   A  B
0  1  2
1  3  4

In [4]:
import pandas as pd
marks_data=pd.DataFrame({
    'ID': {0: 23, 1: 43, 2: 12,
           3: 13, 4: 67, 5: 89,
           6: 90, 7: 56, 8: 34},

    'Name': {0: 'Ram', 1: 'Deep',
             2: 'Yash', 3: 'Aman',
             4: 'Arjun', 5: 'Aditya',
             6: 'Divya', 7: 'Chelsea',
             8: 'Akash'},

    'Marks': {0: 89, 1: 97, 2: 45, 3: 78,
              4: 56, 5: 76, 6: 100, 7: 87,
              8: 81},

    'Grade': {0: 'B', 1: 'A', 2: 'F', 3: 'C',
              4: 'E', 5: 'C', 6: 'A', 7: 'B',
              8: 'B'}
})
file_name='MarksData.xlsx'
marks_data.to_excel(file_name)
print("data is succesfully turned to a table")
df=pd.read_excel("MarksData.xlsx")
print(df)

data is succesfully turned to a table
   Unnamed: 0  ID     Name  Marks Grade
0           0  23      Ram     89     B
1           1  43     Deep     97     A
2           2  12     Yash     45     F
3           3  13     Aman     78     C
4           4  67    Arjun     56     E
5           5  89   Aditya     76     C
6           6  90    Divya    100     A
7           7  56  Chelsea     87     B
8           8  34    Akash     81     B

In [15]:
import pandas as pd
df=pd.read_csv('data.csv')
print(df)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [16]:
df['Duration']

0      60
1      60
2      60
3      45
4      45
       ..
164    60
165    60
166    60
167    75
168    75
Name: Duration, Length: 169, dtype: int64

In [18]:
df.query("Duration>25 & Calories==400")

     Duration  Pulse  Maxpulse  Calories
43         60    111       138     400.0
146        60    107       136     400.0

In [19]:
df.query("Duration>24 | Calories==400")

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[158 rows x 4 columns]

In [20]:
col='Duration'
df.query(f"{col}>25")

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[157 rows x 4 columns]

In [21]:
Calories_limit=300
df.query("Calories>@Calories_limit")

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
4          45    117       148     406.0
6          60    110       136     374.0
..        ...    ...       ...       ...
155        60    111       151     368.5
158        60    114       150     382.8
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[88 rows x 4 columns]

In [2]:
import pandas as pd
df=pd.read_csv('data_cleaning_sample.csv')
print(df)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [5]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [7]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [8]:
print(df)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [11]:
df.dropna() # nan wale hat gaye

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [20]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [23]:
df.fillna(0)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  20.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  20.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5       20  28.0        Delhi      F     eve@domain.com          20
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  20.0        Delhi      M    charlie@example  20-07-2021

In [28]:
df["Age"].mean()

np.float64(25.833333333333332)

In [8]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [9]:
df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date  fun
0    Alice  25.0     New York      F  alice@example.com  01-05-2021  bad
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021  bad
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020  bad
4    David  22.0       Mumbai      M  david@example.com  12-11-2019  bad
5      NaN  28.0        Delhi      F     eve@domain.com         NaN  bad

In [10]:
df.duplicated(subset=['Name','Age'])

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [12]:
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [13]:
df

      Name   Age         City Gender              Email   Join Date  fun
0    Alice  25.0     New York      F  alice@example.com  01-05-2021  bad
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021  bad
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020  bad
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021  bad
4    David  22.0       Mumbai      M  david@example.com  12-11-2019  bad
5      NaN  28.0        Delhi      F     eve@domain.com         NaN  bad
6    Alice  25.0     New York      F  alice@example.com  01-05-2021  bad
7    Alice  25.0     New York      F  alice@example.com  01-05-2021  bad
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021  bad

In [17]:
df['City'].str.contains('Delhi',case=False)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [22]:
type(df['City'].str.contains('delhi',case=False))

pandas.core.series.Series

In [23]:
df['Email'].str.split(".")

0    [alice@example, com]
1       [charlie@example]
2      [bob@example, com]
3       [charlie@example]
4    [david@example, com]
5       [eve@domain, com]
6    [alice@example, com]
7    [alice@example, com]
8       [charlie@example]
Name: Email, dtype: object

In [26]:
type(df['Email'].str.split("@")[0])

list

In [27]:
df2=df.dropna().copy()
df2

    Name   Age         City Gender              Email   Join Date  fun
0  Alice  25.0     New York      F  alice@example.com  01-05-2021  bad
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020  bad
4  David  22.0       Mumbai      M  david@example.com  12-11-2019  bad
6  Alice  25.0     New York      F  alice@example.com  01-05-2021  bad
7  Alice  25.0     New York      F  alice@example.com  01-05-2021  bad

In [30]:
df2["Age"]=df2['Age'].astype(int)
df2

    Name  Age         City Gender              Email   Join Date  fun
0  Alice   25     New York      F  alice@example.com  01-05-2021  bad
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020  bad
4  David   22       Mumbai      M  david@example.com  12-11-2019  bad
6  Alice   25     New York      F  alice@example.com  01-05-2021  bad
7  Alice   25     New York      F  alice@example.com  01-05-2021  bad

In [32]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 7
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      object
 1   Age        5 non-null      int64
 2   City       5 non-null      object
 3   Gender     5 non-null      object
 4   Email      5 non-null      object
 5   Join Date  5 non-null      object
 6   fun        5 non-null      object
dtypes: int64(1), object(6)
memory usage: 320.0+ bytes

In [34]:
def isminor(x):
    return "Adult" if x>=25 else "minor"
df2["Age Group"]=df2["Age"].apply(isminor)

In [35]:
df2

,Name,Age,City,Gender,Email,Join Date,fun,Age Group
0,Alice,25,New York,F,alice@example.com,01-05-2021,bad,Adult
2,Bob,30,Los Angeles,M,bob@example.com,15-06-2020,bad,Adult
4,David,22,Mumbai,M,david@example.com,12-11-2019,bad,minor
6,Alice,25,New York,F,alice@example.com,01-05-2021,bad,Adult
7,Alice,25,New York,F,alice@example.com,01-05-2021,bad,Adult