In [1]:
a=10
print(10)

10

In [2]:
import pandas as pd
df=pd.read_csv("datas.csv")
df

,Actor,Film,Year,Genre,BoxOffice(Net Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.9
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5

In [8]:
df.sort_values("BoxOffice(Net Crore)",ascending=False)

,Actor,Film,Year,Genre,BoxOffice(Net Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.9
7,Hrithik Roshan,War,2019,Action,475,6.5
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3

In [10]:
df

,Actor,Film,Year,Genre,BoxOffice(Net Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.9
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5

In [12]:
df.sort_values(["BoxOffice(Net Crore)","Year"])

,Actor,Film,Year,Genre,BoxOffice(Net Crore),IMDb
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
7,Hrithik Roshan,War,2019,Action,475,6.5
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.9
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [13]:
df.sort_index()

,Actor,Film,Year,Genre,BoxOffice(Net Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.9
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5

In [14]:
df2=df.sort_values(["Year","IMDb"]).copy()
df2

,Actor,Film,Year,Genre,BoxOffice(Net Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.9
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Hrithik Roshan,War,2019,Action,475,6.5
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [15]:
df2.reset_index(drop=True ,inplace=True)

In [16]:
df2

,Actor,Film,Year,Genre,BoxOffice(Net Crore),IMDb
0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.9
2,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
3,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
4,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
5,Hrithik Roshan,War,2019,Action,475,6.5
6,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
7,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [22]:
df2["Rank"]=df2["IMDb"].rank(ascending=False,method="dense")

,Actor,Film,Year,Genre,BoxOffice(Net Crore),IMDb,Rank
0,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.9,6.0
2,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,5.0
3,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,3.0
4,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
5,Hrithik Roshan,War,2019,Action,475,6.5,7.0
6,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,8.0
7,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,4.0

In [24]:
import pandas as pd

df = pd.DataFrame({
    "Department": ["HR", "HR", "IT", "IT", "Marketing", "Marketing", "Sales", "Sales"],
    "Team": ["A", "A", "B", "B", "C", "C", "D", "D"],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Salary": [85, 90, 78, 85, 92, 88, 75, 80],
    "Age": [23, 25, 30, 22, 28, 26, 21, 27],
    "JoinDate": pd.to_datetime([
        "2020-01-10",
        "2020-02-15",
        "2021-03-20",
        "2021-04-10",
        "2020-05-30",
        "2020-06-25",
        "2021-07-15",
        "2021-08-01"
    ])
})

print(df)

df.groupby("Department")["Age"].mean()

  Department Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
2         IT    B      M      78   30 2021-03-20
3         IT    B      F      85   22 2021-04-10
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25
6      Sales    D      M      75   21 2021-07-15
7      Sales    D      F      80   27 2021-08-01

Department
HR           24.0
IT           26.0
Marketing    27.0
Sales        24.0
Name: Age, dtype: float64